export const TOGGLE_PRODUCT_TO_CART = 'TOGGLE_PRODUCT_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const GET_PRODUCTS_FOR_CART = 'GET_PRODUCTS_FOR_CART';
export const CLEAR_LIST_PRODUCTS = 'CLEAR_LIST_PRODUCTS';
export const SET_INITIAL_ORDERING_PRODUCTS = 'SET_INITIAL_ORDERING_PRODUCTS';
export const REMOVE_ORDER_OF_ORDERING_LIST = 'REMOVE_ORDER_OF_ORDERING_LIST';
export const UPDATE_ORDERING_PRODUCTS = 'UPDATE_ORDERING_PRODUCTS';
