export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const PAGE_INCREMENT = 'PAGE_INCREMENT';
export const CHECK_SHOW_MORE = 'CHECK_SHOW_MORE';
