export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID';
export const PAGE_INCREMENT = 'PAGE_INCREMENT';
export const CHECK_SHOW_MORE = 'CHECK_SHOW_MORE';
export const SEARCH_RESULT = 'SEARCH_RESULT';
export const ENTRY_QUERY_STRING = 'ENTRY_QUERY_STRING';
export const RESET_PAGE = 'RESET_PAGE';
